apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyx-nestjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nyx-nestjs
  template:
    metadata:
      labels:
        app: nyx-nestjs
    spec:
      containers:
        - name: nyx-nestjs
          image: 200262187471.dkr.ecr.ap-southeast-1.amazonaws.com/jeremy-api-nestjs:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nyx-nestjs-service
spec:
  selector:
    app: nyx-nestjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer